
server:
  port: 7002
  servlet:
    context-path: /eureka-client

spring:
  application:
    name: eureka-client

eureka:
  client:
    # 是否开启注册服务
    register-with-eureka: true
    # 是否拉取服务列表
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka-explore/eureka/

  instance:
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
    # 服务续约任务的调用间隔时间，默认为30秒
    lease-renewal-interval-in-seconds: 30
    prefer-ip-address: true